config/routes.rb
Bookclub::Application.routes.draw do
  resources :cosicas

  resources :videos

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :users

  root :to => "videos#index"
  if Rails.env.development?
    mount VideosMailer::Preview => 'mail_view'
  end

  resources :books

  match '/rsvp/update' => "rsvp#update", as: :rsvp_update
  match '/games/:game/send_mailer' => "games#send_mailer", as: :game_send_mailer
  resources :games

  match '/marriages/load' => "marriages#load"
  resources :marriages

end

app/models/video.rb
class Video < ActiveRecord::Base
  before_create :extract_guid

  def extract_guid
    uri = URI.parse(self.url)
    query = Rack::Utils.parse_query(uri.query)
    self.guid = query['v'] || uri.path.match(/\/v\/([-_A-Z0-9]+)/i)[1]
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_filter :authenticate_user!, except: [:index]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all(order: 'created_at desc')
    @video = Video.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    if request.xhr?
      @video.views ||= 1
      @video.views += 1
      @video.save!
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
      format.js   { render 'youtube', layout: false }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    @gm_id = params[:gm_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
      format.js
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        VideosMailer.new_video(@video).deliver

        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
        format.js   { render :nothing }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
        format.js   { render :nothing }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= form_for(@video) do |f|
  - if @video.errors.any?
    #error_explanation
      %h2
        = pluralize(@video.errors.count, "error")
        prohibited this video from being saved:
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre
    %br/
    = f.text_field :name
  .field
    = f.label 'Youtube URL'
    %br/
    = f.text_field :url
  .field
    = f.label :dirección
    %br/
    = f.text_field :address, :readonly => true
  .field
    = f.label :región
    %br/
    = f.text_field :state, :readonly => true
  .field
    = f.label :país
    %br/
    = f.text_field :country, :readonly => true

  .field.hidden
    = f.text_field :latitude
  .field.hidden
    = f.text_field :longitude
  .field.hidden
    = f.text_field :content

app/views/videos/edit.html.haml
%h1 Editing video
= render 'form'
= link_to 'Show', @video
|
\#{link_to 'Back', videos_path}

app/views/videos/index.html.haml
%h1 Mapa

%br/

%span.hidden#videos_url{:'data-url' => videos_url}

#map_canvas.map.rounded

%h1 Últimos 3 vídeos

#listing
  %table{:cellpadding => 10, :cellspacing => 10}
    %tr
    - @videos[0..2].each do |video|
      %td
        %iframe{:class => 'youtube-player', :type => 'text/html', :width => 384, :height => 200,
              :src => "http://www.youtube.com/embed/#{video.guid}", :frameborder => 0}


#dialog{style: 'display: none'}
  = render 'form', layout: false

#marker_content.hidden
  /
    %iframe{:class => 'youtube-player', :type => 'text/html', :width => 384, :height => 200,
          :src => "http://www.youtube.com/embed/guid", :frameborder => 0}

app/views/videos/new.html.haml
%h1 New video
= render 'form'
= link_to 'Back', videos_path

app/views/videos/new.js.haml
= render 'form', layout: false

app/views/videos/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @video.name
%p
  %b Url:
  = @video.url
%p
  %b Views:
  = @video.views
= link_to 'Edit', edit_video_path(@video)
|
\#{link_to 'Back', videos_path}

app/views/videos/youtube.js.haml
-#%object{:classid => "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000", :height => 200, :width => 384}
-#  %param{:name => "movie", :value => "http://www.youtube.com/v/#{@video.guid}&fs=1&rel=0"}
-#  %param{:name => "allowFullscreen", :value => "true"}
-#  %param{:name => "allowscriptaccess", :value => "always"}
-#  %param{:name => "wmode", :value => "opaque"}
-#  %embed{:allowfullscreen => "true", :allowscriptaccess => "always", :height => 200,
-#          :src => "http://www.youtube.com/v/#{@video.guid}&fs=1&rel=0", :type => "application/x-shockwave-flash",
-#          :width => 384, :wmode => "opaque"}

%iframe{:class => 'youtube-player', :type => 'text/html', :width => 384, :height => 200,
        :src => "http://www.youtube.com/embed/#{@video.guid}", :frameborder => 0}